ARDUINO_DIR=/usr/share/arduino
BOARD_TAG=uno
ARDUINO_PORT=/dev/ttyACM0
ARDUINO_LIBS=
ARDMK_DIR=/home/pi/code/rpi/arduino/arduino-make

include /home/pi/code/rpi/arduino/arduino-make/arduino-mk/Arduino.mk

AVR_TOOLS_PATH=/usr/bin
AVRDUDE_CONF=/etc/avrdude.conf

